Don't build i686 binaries
Build is failing because it can't find libcurl:
ValueError: Cannot repair wheel, because required library
"libssl.so.10" could not be located

Someone who cares about this can fix it